### ISSUE TITLE
Option "ignore about:newtab + about:home" does not work when duplicating tabs

### ISSUE THREAD

**Issue by WhiteSp1rit** [igorlogius/dont-open-duplicate-tabs#11]
With the option "ignore about:newtab + about:home" turned on, when you duplicate a blank tab, all blank tabs will be closed instead of being ignored.

Happens with both regular blank tabs, and the ones where an extension replaces them (like Group Speed Dial)

**To Reproduce**
1. Enable "ignore about:newtab + about:home" option
2. Open several new blank tabs
3. Duplicate one of them
4. All of them except for one will be closed

**Expected behavior**
Blank tabs should be ignored.

**Comment by igorlogius** [comment]
Thanks for reporting the issue. 
I'll try to replicate it.

**Comment by igorlogius** [comment]
@WhiteSp1rit  

On first try i could not replicate your issue.
I tried duplication both with the browser built-in and the addon context option.  
Which method of duplication did you use?

It would be helpful for me to know which other preferences where activ, besides "ignore about:newtab + about:home". Could you share a screenshot of the addon preferences? Thanks.

**Comment by igorlogius** [comment]
@WhiteSp1rit 

The `ignore about:newtab + about:home` option will be removed in the next update, since 
the Whitelist can already be used to make exceptions for the `about:` pages.

**Comment by WhiteSp1rit** [comment]
> @WhiteSp1rit
> 
> The `ignore about:newtab + about:home` option will be removed in the next update, since the Whitelist can already be used to make exceptions for the `about:` pages.

How would I add the pages that do not show their address to the whitelist? 
New tabs which are replaced by addons (Group Speed Dial) have blank address, so there is nothing to copy.

**Comment by igorlogius** [comment]
The only pages that should not show their addresses should be `about:newtab` and `about:home`  
I suspect Group Speed dial just replacing/overwriting those. 

Try these 

- `^about:newtab$`  
- `^about:home$`

for the whitelist. 

If that doesn't work, let me know and i'll take a better look into it.
