### ISSUE TITLE
Ability to close pre-existing duplicate tabs with a click

### ISSUE THREAD

**Issue by stephenkoo** [igorlogius/dont-open-duplicate-tabs#12]
**Is your feature request related to a problem? Please describe.**
I sometimes forget to turn the extension back on when I need to disable it, causing me to open multiple duplicate tabs  before realizing it is off.

**Describe the solution you'd like**
I would like a way to click on the extension icon, and easily see and close duplicates grouped together (similar to [Duplicate Tabs Closer](https://addons.mozilla.org/en-US/firefox/addon/duplicate-tabs-closer-updated/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search))

**Describe alternatives you've considered**
I have tried just remembering to turn it back on.

**Additional context**

**Comment by igorlogius** [comment]
Hi, thanks for taking the time to leave a suggestion. 

Extending the UI like what DTC does would be a lot of work and would definitely take me a lot time to get done. 

What i could do in a relatively short timeframe would be to add an option which allows you to set a time after which the addon will automatically be reactived after it was paused. - A reactivation/unpause timer setting of sorts.

`Q1: Would that work for you or is the filter UI absolutely necessary for your usecase? `

I just had one other question, that just came to me: 

`Q2: Is there any reason why you cant use DTC and DODT together?`

I mean i did not test the addons together, but if there is some kind of issue with them, it would be nice to know about. 

One other thing, you might not have noticed/known about. 

`A1: Dups will only get closed if they are in the same window.`

So currently you have the option to open the dups into another window to let them stay open.  
Not sure if that would be something you'd like to try ... but i thought i'd let you know about it, just in case. 

Later.

**Comment by igorlogius** [comment]
Version 1.8.10 
now has a tab strip context menu entry to trigger a manual duplicate removal. 

![snip_20230311-210657](https://user-images.githubusercontent.com/67047467/224509448-678364f7-6c24-478d-8191-9ec5da202bbf.png)
