### ISSUE TITLE
Force open duplicate tab

### ISSUE THREAD

**Issue by GitUser200607** [igorlogius/dont-open-duplicate-tabs#16]
It could seem strange, but i WANT to open duplicate tab. I open it with context menu "Duplicate Tab". How can I tell the extension not to close THIS tab at this time? 
Can we have some shortcut to skip verification?
Or maybe we can ignore tabs duplicated with context menu?

**Comment by igorlogius** [comment]
> How can I tell the extension not to close THIS tab at this time?

The feature exist, but you have to enable it.
You can either set a shortcut key for the action 
![Screenshot_2024-02-04_10-40-33](https://github.com/igorlogius/dont-open-duplicate-tabs/assets/67047467/66e3d100-7623-49d8-b6fe-4d56cbad984f)

or enable the "Force Duplicate Tab" option tab context entry on the preferences
![Screenshot_2024-02-04_10-40-51](https://github.com/igorlogius/dont-open-duplicate-tabs/assets/67047467/d3ae5297-aecf-442c-892e-0d7d3ce9d6eb)

**Comment by GitUser200607** [comment]
Thank you!
