### ISSUE TITLE
Option to also work for "manual" new tabs

### ISSUE THREAD

**Issue by forteller** [igorlogius/dont-open-duplicate-tabs#4]
Hi. Thank you for a life saver of an extension!

My one problem is that I often manually open a new tab and go to a page that I already have open in another tab, without knowing it. Right now only when you open links in new tabs Don't open duplicate tabs springs to action, but if you enter the URL in the addressbar yourself it does not help you. I totally understand that this might be a good thing, maybe even the best thing for most people. But an option to also stop you from duplicating your tabs in this "manual" way could be very useful for some.

I'd love to see this implemented, if possible, as a "turned off by default" setting.

Thank you!

**Comment by igorlogius** [comment]
I updated the addon with 2 additional options (1.2.2). Try unchecking the "only with opener"  option. 
Duplicate Tab prevention will then include all tabs opened without an opener Tab (for example from Bookmarks, History, Manually entered and external apps) I currently don't have a good way to further distinguish between those kind of created tabs, so i hope this option works for you.

**Comment by forteller** [comment]
Wow, that was amazingly fast! Thank you so much! Great work!

**Comment by forteller** [comment]
Oh, but one thing I noticed now, that might be an issue:

I use the extension Auto tab discard to save resources when I don't use a tab for a while. I had two identical tabs already opened, but discarded by Auto tab discard. When now selected one of them Don't open duplicate tabs closed that tab and sent me to the other tab. I'm not sure that's a good way to do it. That is, if you already have opened two identical tabs, maybe that should be respected? I'm not sure, just wanted to bring it up. Thanks again :)

**Comment by igorlogius** [comment]
Added to option to "ignore discarded" tabs (default: false, needs to enabled)

FYI: debugging issues between addons is very tedious (aka. out-of-scope). I am making an excpetion because the discarded state can also be invoked by the browser itself.

For further issues, please be so kind and open a new ticket. Helps to keep things organized. Thanks.
