### ISSUE TITLE
Is it possible to add a "close old tab" setting?

### ISSUE THREAD

**Issue by WhiteSp1rit** [igorlogius/dont-open-duplicate-tabs#5]
Is it possible to add a "close the old tab / keep the new tab" setting?

A setting would change the addon behaviour to keep the newly opened tab while closing the old ones, 
instead of closing the newly opened tab and keeping an old one like it does now.

**Comment by igorlogius** [comment]
I'll see what i can do.

**Comment by igorlogius** [comment]
Option added to version 1.4.3.
Hope it helps.
