### ISSUE TITLE
Do not block intentional duplicates

### ISSUE THREAD

**Issue by Speravir** [igorlogius/dont-open-duplicate-tabs#6]
Firefox has built-in ability to create duplicate tabs. I do not know which English term is used for it, but I suppose it’s called “Clone tab”.

With your addon installed this features is blocked in the moment. This behaviour started with one of the latest updates, but because coincidentally both Firefox and your addon had updates I cannot say whether it is caused by the addon or a change in Firefox. (In fact, I tested two other similar addons, and both blocked intentional cloning, too.)

I am not a developer and do not know, how a solution could look like. Being a built-in feature there must be some API or whatever it is called in this case.

**Comment by igorlogius** [comment]
> there must be some API or whatever it is called in this case.

Sadly there is not AFAIK. 
Duplicating a tab via the manual option can currently not destinguished. 
And i dont think mozilla will extend the addon API to contain event which allow to monitor user actions.  I've already seen some examples where they intentionally dont implement these features, because this might be used to track/monitor user behaviour. 

So for the time being there is nothing i can do about this. Sorry.

**Comment by igorlogius** [comment]
As a workaround, i can currently only suggest that you use the toolbar icon to temporary disable the duplication prevention and after cloneing click it again to re-enable it.

**Comment by WhiteSp1rit** [comment]
I've checked "Tab Deduper" addon, and it has an option of "Keep Explicitly Duplicated Tabs", which does what it says - it will not close the tabs duplicated by you. So might be possible to just ask that addon's dev what method they used.

**Comment by igorlogius** [comment]
I'll take a look at what they are doing. Thanks for the hint.

**Comment by igorlogius** [comment]
@WhiteSp1rit  

"Tab Deduper"'s manual duplication detection seems incomplete/faulty. 
 
It only seems to  work when i manually duplicate the active tab.
If i try to duplicate any inactive tab, it closes the duplicated one.  

Going by the description on the option/setting 

`Tabs created by the “Duplicate Tab" option will not be automatically removed.`

this is seems incorrect. 

Can you confirm this observation?

**Comment by igorlogius** [comment]
@Speravir

I thought of one other workaround and added it to version `1.7.4`. (for testing)
The tab/tabstrip context menu now contains a "Force Duplicate Tabs" entry.

![snip_20221028-184759](https://user-images.githubusercontent.com/67047467/198737735-673d10d1-80fa-4af4-8a59-59f588f517fa.png)

@WhiteSp1rit 

This new entry should behaves as expected when duplicating unfocused or multiple selected tabs, as the original duplication mechanic does. 

If i'll find a better solution, i'll update the addon.

**Comment by igorlogius** [comment]
@Speravir 

> but now you could consider hiding the default menu entry 

Addons can not manipulate the context via their api, but firefox has some files you can edit to make such modifications. 

I'd suggest asking on https://reddit.com/r/FirefoxCSS and you will very likely get some help on how to hide (and/or rearange) the context menus.

Hope this info helps.
