### ISSUE TITLE
Avoid notification for whitelist matches

### ISSUE THREAD

**Issue by Speravir** [igorlogius/dont-open-duplicate-tabs#7]
I like the notification when a duplicate tab has been blocked. but I find it annoying getting a notification when a whitelist match is recognized.

I am active in Wikimedia universe and therefore have a quite general whitelist entry
```
.+\.(mediawiki|wikimedia|wikipedia|wikidata)\.org.*
```
(in fact, it’s even longer).

But then I get a notification for **every** new page. It does not matter, whether the _exact_ same page is already opened. For now, I disabled this addon feature, but as said above I actually like it.

**Comment by igorlogius** [comment]
I'll see what i can do.

**Comment by igorlogius** [comment]
Option added to version `1.6.4`

![snip_20221028-095240](https://user-images.githubusercontent.com/67047467/198534235-41d3340c-5aff-45ee-901a-14f7b30cc8a7.png)
