### ISSUE TITLE
Whitelist design

### ISSUE THREAD

**Issue by Speravir** [igorlogius/dont-open-duplicate-tabs#9]
As follow-up to #8 some rough suggestions about the whitelist design:

Either add a note above the whitelist that existing whitelist entries can be edited and the save button has to be pressed afterwards or add an own save button in the actions column if something has changed in an entry.

Also, I would prefer that the empty line is hidden by default and only visible after pressing an “Add new” button or shorter only “New”. This could put in the actions column, too, or above the whitelist, but certainly then the button name has to be longer (“New whitelist entry” or similar?).

**Comment by igorlogius** [comment]
Thanks for taking the time to give some feedback. 
I'll see what i can do to make the whitelist more intutive to use. 
Might take me a bit of time, since i am a little busy in the comming weeks. 
Nonetheless, i'll try to get to it on a weekend or something.

**Comment by igorlogius** [comment]
I opted to rather not completely redesign the whitelist with something like tabulator ... so i just made some minor changes and added a note.
